/*
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (99, 123.45);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (100, 1.00);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (101, 150.00);

INSERT INTO CASH_CARD( AMOUNT, OWNER) VALUES (123.00, 'sarah1');
INSERT INTO CASH_CARD( AMOUNT, OWNER) VALUES (1.00, 'sarah1');
INSERT INTO CASH_CARD(AMOUNT, OWNER) VALUES (150.00, 'sarah1');
INSERT INTO CASH_CARD(AMOUNT, OWNER) VALUES (357.00, 'sarah1');
INSERT INTO CASH_CARD(AMOUNT, OWNER) VALUES (450.00, 'sarah1');
INSERT INTO CASH_CARD(AMOUNT, OWNER) VALUES (450.00, 'sarah1');
INSERT INTO CASH_CARD(AMOUNT, OWNER) VALUES (200.00, 'kumar2');
*/